name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
website: "${project.url}"
permissions:
    minebans.antispam.exempt:
        description: Players will this permission will be allowed to spam.
        default: op